// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VariacaoAtivo.Infra;

#nullable disable

namespace VariacaoAtivo.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230324214406_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VariacaoAtivo.Dominio.Entidade.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstDateTrade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("VariacaoAtivo.Dominio.Entidade.Pregao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("Close")
                        .HasColumnType("real");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime2");

                    b.Property<float?>("High")
                        .HasColumnType("real");

                    b.Property<int>("IdAtivo")
                        .HasColumnType("int");

                    b.Property<float?>("Low")
                        .HasColumnType("real");

                    b.Property<float?>("Open")
                        .HasColumnType("real");

                    b.Property<int?>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAtivo");

                    b.ToTable("Pregoes");
                });

            modelBuilder.Entity("VariacaoAtivo.Dominio.Entidade.Pregao", b =>
                {
                    b.HasOne("VariacaoAtivo.Dominio.Entidade.Ativo", "Ativo")
                        .WithMany("Pregoes")
                        .HasForeignKey("IdAtivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("VariacaoAtivo.Dominio.Entidade.Ativo", b =>
                {
                    b.Navigation("Pregoes");
                });
#pragma warning restore 612, 618
        }
    }
}
