IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'VAR_ATIVO') 
BEGIN
	CREATE DATABASE VAR_ATIVO
	CREATE LOGIN WEB_API WITH PASSWORD = '$(MSSQL_WEB_API_PASSWORD)'
END
GO

USE [VAR_ATIVO]
GO
	
IF NOT EXISTS(SELECT * FROM sys.sysusers WHERE name = 'WEB_API') 
BEGIN	
	CREATE USER [WEB_API] FOR LOGIN [WEB_API]
	GRANT CREATE TABLE TO [WEB_API]
	exec('CREATE SCHEMA WEB_API AUTHORIZATION WEB_API');
	ALTER USER [WEB_API] WITH DEFAULT_SCHEMA = [WEB_API]
END
GO







